site_name: go-dito docs
site_url: https://docs.dito.icb4dc0.de

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - content.code.copy
    - content.code.select

plugins:
  - search

nav:
  - Home:
      - About: index.md
      - Getting Started: getting_started.md
  - Features:
      - Plain HTTP: features/plain_http.md
      - OpenAPI: features/openapi.md
      - GraphQL: features/graphql.md
  - Configuration:
      - Basics: configuration/basics.md
      - Plain HTTP: configuration/plain_http.md
  - DSL:
      - Intro: dsl/intro.md
      - Matchers: dsl/matchers.md
      - Handlers: dsl/handlers.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
