name: Go
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    branches:
      - main

permissions:
  checks: write
  contents: write
  packages: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: imjasonh/setup-crane@v0.1
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          fetch-tags: "true"

      - name: Login to Github Container Registry
        run: |
          crane auth login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v3

      - name: Start bazel cache
        run: |
          arch=$(uname -m | sed -E 's/x86_64/amd64/g')
          os=$(uname -s | tr '[:upper:]' '[:lower:]')

          sudo curl -o /usr/local/bin/bazel-remote https://code.icb4dc0.de/api/packages/prskr/generic/bazel-remote-$os-$arch/1.1.1/bazel-remote-$os-$arch
          sudo chmod +x /usr/local/bin/bazel-remote
          mkdir -p /tmp/bazel-remote
          /usr/local/bin/bazel-remote --dir /tmp/bazel-remote --max_size 1000 --http_address=":3055" > /tmp/bazel_remote.log 2>&1 &

      - uses: bazel-contrib/setup-bazel@0.14.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ matrix.os }}-${{ github.workflow }}
          repository-cache: true

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-version-file: go.mod
          go-package: ./...
          repo-checkout: false

      - name: Test
        run: |
          bazel \
            --bazelrc=$GITHUB_WORKSPACE/.github/workflows/ci.bazelrc \
            test //...

      - name: Archive Bazel-Remote logs
        uses: actions/upload-artifact@v4
        with:
          name: bazel-remote-logs-${{ matrix.os }}
          path: |
            /tmp/bazel_remote.log

      - name: Build image
        run: |
          bazel \
            --bazelrc=$GITHUB_WORKSPACE/.github/workflows/ci.bazelrc \
            run //:push
        if: "github.ref_name == 'main'"
